### ISSUE TITLE
homeBannerButtonUrl theme setting removed

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-frescobox#31]
There is currently a theme setting for the label of the banner button on the home page (code is "homeBannerButtonText") but there should be a related theme setting for the banner button URL (code should be "homeBannerButtonUrl"), which appears to have been removed recently. We need to add this back...

**Comment by robotpony** [comment]
It was removed (likely accidentally) in this commit:

https://github.com/lemonstand/lscloud-theme-frescobox/commit/0a2b60f67c637b965b40e4b69490e2f7b5e1a436#diff-eb296f928eeca82b4333c03266bff88e

(Should be able to grab the code from there).
